Update build-deploy.yml

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -89,6 +89,10 @@ jobs:
       # Étape 9 : Construire et empaqueter l'application Java
       - name: Build and package Java application
         run: mvn clean package -DskipTests
+          if [ $? -ne 0 ]; then
+         echo "Maven build failed"
+         exit 1
+         fi
 
       - name: Afficher l'emplacement du fichier JAR
         run: |
