modif des variables denv aws et ecs build-deploy.yml

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -56,19 +56,31 @@ jobs:
           APPLICATION: smartlib-catalog
           SERVICE: catalog-service
         run: |
-          echo "environment=${ENVIRONMENT}" >> $GITHUB_OUTPUT
-          echo "application=${APPLICATION}" >> $GITHUB_OUTPUT
-          echo "service=${SERVICE}" >> $GITHUB_OUTPUT
-          if [ "${ENVIRONMENT}" = "dev" ]; then
+          # Définition des variables nécessaires pour le déploiement
+          ENVIRONMENT="${{ steps.split_pre.outputs._1 }}"  # Récupération de l'environnement (dev ou prod)
+          APPLICATION="smartlib-catalog"                  # Nom de l'application
+          SERVICE="catalog-service"                       # Nom du service
+
+          # Vérification que les variables sont définies
+          if [[ -z "$ENVIRONMENT" || -z "$APPLICATION" || -z "$SERVICE" ]]; then
+            echo "Error: One of the environment variables is missing."
+            exit 1
+          fi
+
+          # Configuration des clés AWS selon l'environnement
+          if [ "$ENVIRONMENT" = "dev" ]; then
             echo "awsAccessKey=${{ secrets.DEV_ADMIN_AWS_ACCESS_KEY }}" >> $GITHUB_OUTPUT
             echo "awsSecretKey=${{ secrets.DEV_ADMIN_AWS_SECRET_KEY }}" >> $GITHUB_OUTPUT
-            echo "awsDefaultRegion=eu-north-1" >> $GITHUB_OUTPUT
-          elif [ "${ENVIRONMENT}" = "prod" ]; then
-            echo "awsAccessKey=PROD_ADMIN_AWS_ACCESS_KEY" >> $GITHUB_OUTPUT
-            echo "awsSecretKey=PROD_ADMIN_AWS_SECRET_KEY" >> $GITHUB_OUTPUT
-            echo "awsDefaultRegion=eu-north-1" >> $GITHUB_OUTPUT
+          elif [ "$ENVIRONMENT" = "prod" ]; then
+            echo "awsAccessKey=${{ secrets.PROD_ADMIN_AWS_ACCESS_KEY }}" >> $GITHUB_OUTPUT
+            echo "awsSecretKey=${{ secrets.PROD_ADMIN_AWS_SECRET_KEY }}" >> $GITHUB_OUTPUT
           fi
-          echo "fullServiceName=${ENVIRONMENT}-${APPLICATION}-${SERVICE}" >> $GITHUB_OUTPUT
+
+          # Configuration des noms ECS
+          echo "ecsCluster=${ENVIRONMENT}-${APPLICATION}-${SERVICE}-fgcluster" >> $GITHUB_OUTPUT
+          echo "ecsService=${ENVIRONMENT}-${APPLICATION}-${SERVICE}-fgservice" >> $GITHUB_OUTPUT
+
+
 
       # Étape 7 : Configurer les credentials AWS
       - name: Configure AWS credentials
