Update build-deploy.yml

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -63,12 +63,10 @@ jobs:
             echo "awsAccessKey=${{ secrets.DEV_ADMIN_AWS_ACCESS_KEY }}" >> $GITHUB_OUTPUT
             echo "awsSecretKey=${{ secrets.DEV_ADMIN_AWS_SECRET_KEY }}" >> $GITHUB_OUTPUT
             echo "awsDefaultRegion=eu-west-1" >> $GITHUB_OUTPUT
-            #echo "springProfile=dev" >> $GITHUB_OUTPUT
           elif [ "${ENVIRONMENT}" = "prod" ]; then
             echo "awsAccessKey=PROD_ADMIN_AWS_ACCESS_KEY" >> $GITHUB_OUTPUT
             echo "awsSecretKey=PROD_ADMIN_AWS_SECRET_KEY" >> $GITHUB_OUTPUT
             echo "awsDefaultRegion=eu-west-1" >> $GITHUB_OUTPUT
-            #echo "springProfile=prod" >> $GITHUB_OUTPUT
           fi
           echo "fullServiceName=${ENVIRONMENT}-${APPLICATION}-${SERVICE}" >> $GITHUB_OUTPUT
 
@@ -90,14 +88,15 @@ jobs:
       - name: Build and package Java application
         run: mvn clean package -DskipTests
           if [ $? -ne 0 ]; then
-         echo "Maven build failed"
-         exit 1
-         fi
+           echo "Maven build failed"
+           exit 1
+          fi
 
       - name: Afficher l'emplacement du fichier JAR
         run: |
            ls -alh target/  # Vérifie l'existence de app.jar
            test -f target/app.jar || (echo "Error: app.jar not found" && exit 1)
+
       ###############################
       # Catalog
       ###############################
@@ -108,18 +107,11 @@ jobs:
         uses: ./.github/actions/publish-api-image
         with:
           maven-environment: ${{ steps.vars.outputs.environment }}
-          #spring-profile: ${{ steps.vars.outputs.springProfile }}
-          published-app: target/app.jar
           dockerfile: Dockerfile   # ajuster le chemin de dockerfile
           cmd: "java -jar /app.jar" 
-          main-class: "dev-fplarache-smartlib-catalog"
           image-short-name: repo
-          #image-prefix: ${{ steps.vars.outputs.fullServiceName }}
-          #image-prefix: ""
-          #image-tag: latest # Utilisation de 'latest' pour la version par défaut
           image-tag: ${{ github.sha }}
           ecr-registry: ${{ steps.login-ecr.outputs.registry }}
-          JAVA_APP_PATH: target/app.jar
 
       # Étape 11 : Pusher l'image Docker vers ECR
       - name: Push Docker image to ECR
