Update build-deploy.yml

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -88,9 +88,10 @@ jobs:
       - name: Build and package Java application
         run: mvn clean package -DskipTests
           if [ $? -ne 0 ]; then
-           echo "Maven build failed"
-           exit 1
+          echo "Maven build failed"
+          exit 1
           fi
+
 
       - name: Afficher l'emplacement du fichier JAR
         run: |
